# k8s/01-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
  namespace: blog
data:
  LOG_LEVEL: 'info'
  USERS_SERVICE_URL: 'http://user.blog.svc.cluster.local:8080'
  POST_SERVICE_URL: 'http://post.blog.svc.cluster.local:8080'
  COMMENTS_SERVICE_URL: 'http://comments.blog.svc.cluster.local:8080' # corregido
