apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  namespace: blog
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: blog.local
      http:
        paths:
          # /api/users/...  ->  /u/...
          - path: /api/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user
                port:
                  number: 8080

          # /api/posts/...  ->  /post/...
          - path: /api/posts(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: post
                port:
                  number: 8080

          # /api/comments/...  ->  /v1/...
          - path: /api/comments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments
                port:
                  number: 8080
